# all ducks with their English names

PREFIX ducks: <https://berlinonline.github.io/jinja-rdf-demo/example/ducks/>
PREFIX schema: <https://schema.org/>

CONSTRUCT {
    ?duck schema:name ?name .
}
WHERE {
    ?duck
        a schema:Person ;
        schema:name ?name .
    FILTER(lang(?name) = 'en')
}
ORDER BY ?name